name: Install and Test DOX CLI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Install
        run: |
          curl -LO https://github.com/dopxlab/dox-cli/releases/latest/download/dox-cli.tar.gz
          bash install.sh

      - name: Run CLI
        run: |
          dox configure
          dox deploy
