name: Install and Test DOX CLI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Download and install DOX CLI
      - name: Install DOX CLI
        run: |
          bash <(curl -s https://github.com/dopxlab/dox-cli/releases/latest/download/install.sh)
      
      # Verify the installation
      - name: Verify DOX CLI installation
        run: |
          dox --version

      # Run DOX configure command to test functionality
      - name: Run DOX configure
        run: |
          dox configure
          
      # Additional testing or other functionality
      - name: Additional Test Step
        run: |
          # Example: Run DOX CLI deploy command or any other operation
          dox deploy
