name: Install and Test DOX CLI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download and run the installation script
      - name: Install DOX CLI
        run: |
          curl -s -L -o install.sh https://github.com/dopxlab/dox-cli/releases/latest/download/install.sh && bash install.sh

      # Step 2: Verify the installation
      - name: Verify DOX CLI installation
        run: |
          dox --version

      # Step 3: Run DOX configure command to test functionality
      - name: Run DOX configure
        run: |
          dox configure

      # Step 4: Additional testing or usage
      - name: Additional Test Step
        run: |
          dox deploy
